version: '3.7'

services:
  caddy:
    container_name: fnb
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./fnb:/var/www/html